import pandas
wages=pandas.read_csv("wages.csv")
wages.drop([col for col in wages.columns if 'yearsSchool' in col],axis=1,inplace=True)
cc=(wages.sort_values(by='wage'))
print ("Lowest Earner")
print (cc.head(n=1))
print ("Highest Earner")
print (cc.tail(n=1))
print ("Top 10 Female Earners")
numoffemales=wages[wages['wage']>=wages['wage'].nlargest(10).iloc[-1]]['gender'].eq('female').sum()
print (numoffemales)
